# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'akademisyen_devamsizlik.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 762)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(360, 130, 271, 141))
        self.groupBox_4.setStyleSheet("background-color: rgb(164, 213, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 241, 31))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 130, 291, 141))
        self.groupBox_3.setStyleSheet("background-color: rgb(208, 227, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(164, 213, 255);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(0, 40, 281, 31))
        self.comboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(660, 130, 271, 141))
        self.groupBox_5.setStyleSheet("background-color: rgb(164, 213, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.groupBox_5.setObjectName("groupBox_5")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 40, 261, 31))
        self.comboBox_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(590, 370, 251, 221))
        self.groupBox.setStyleSheet("background-color: rgb(164, 213, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(60, 90, 95, 20))
        self.radioButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.radioButton.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(60, 120, 95, 20))
        self.radioButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.radioButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(130, 370, 461, 221))
        self.groupBox_2.setStyleSheet("background-color: rgb(164, 213, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(130, 50, 311, 22))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 90, 311, 22))
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(460, 680, 131, 71))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(255, 150, 80);\n"
"font: 8pt \"Gill Sans Ultra Bold\";\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(940, 10, 71, 61))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(208, 227, 255);\n"
"background-color: rgb(255, 195, 99);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("geri dönme.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AKADEMİSYEN DEVAMSIZLIK"))
        self.groupBox_4.setTitle(_translate("Form", "ÖĞRENCİ NUMARASI SEÇİNİZ:"))
        self.comboBox.setItemText(0, _translate("Form", "NUMARALAR"))
        self.groupBox_3.setTitle(_translate("Form", "DERS SEÇİNİZ:"))
        self.comboBox_2.setItemText(0, _translate("Form", "DERSLER"))
        self.groupBox_5.setTitle(_translate("Form", "HAFTA SEÇİNİZ:"))
        self.comboBox_4.setItemText(0, _translate("Form", "HAFTALAR"))
        self.comboBox_4.setItemText(1, _translate("Form", "Hafta1"))
        self.comboBox_4.setItemText(2, _translate("Form", "Hafta2"))
        self.comboBox_4.setItemText(3, _translate("Form", "Hafta3"))
        self.comboBox_4.setItemText(4, _translate("Form", "Hafta4"))
        self.comboBox_4.setItemText(5, _translate("Form", "Hafta5"))
        self.comboBox_4.setItemText(6, _translate("Form", "Hafta6"))
        self.groupBox.setTitle(_translate("Form", "DEVAM DURUMU SEÇİNİZ:"))
        self.radioButton.setText(_translate("Form", "GELDİ"))
        self.radioButton_2.setText(_translate("Form", "GELMEDİ"))
        self.groupBox_2.setTitle(_translate("Form", "ÖĞRENCİ BİLGİLERİ:"))
        self.label_2.setText(_translate("Form", "İSİM SOYİSİM:"))
        self.label_8.setText(_translate("Form", "BÖLÜM:"))
        self.pushButton.setText(_translate("Form", "GÜNCELLE"))
        self.pushButton_2.setText(_translate("Form", "GERİ"))
