# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'akademisyen_ana_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 588)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 211, 541))
        self.groupBox_3.setStyleSheet("background-color: rgb(164, 213, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 90, 191, 28))
        self.pushButton_21.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 120, 191, 28))
        self.pushButton_22.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_22.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_23.setGeometry(QtCore.QRect(10, 150, 191, 28))
        self.pushButton_23.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_23.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_23.setObjectName("pushButton_23")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(230, 220, 551, 111))
        self.groupBox.setStyleSheet("background-color: rgb(164, 213, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 55, 281, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(710, 0, 81, 41))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 195, 99);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("çıkış.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AKADEMİSYEN ANA MENÜ"))
        self.groupBox_3.setTitle(_translate("MainWindow", "MENÜ"))
        self.pushButton_21.setText(_translate("MainWindow", "GENEL BİLGİLER"))
        self.pushButton_22.setText(_translate("MainWindow", "NOT GÜNCELLE"))
        self.pushButton_23.setText(_translate("MainWindow", "DEVAMSIZLIK GÜNCELLE"))
        self.groupBox.setTitle(_translate("MainWindow", "AKTİF AKADEMİK DÖNEM BİLGİLERİ"))
        self.label.setText(_translate("MainWindow", "2023-2024 GÜZ DÖNEMİ"))
        self.pushButton_4.setText(_translate("MainWindow", "ÇIKIŞ"))
