# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ana_pencere.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 648)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.akademisyen_butonu = QtWidgets.QPushButton(self.centralwidget)
        self.akademisyen_butonu.setGeometry(QtCore.QRect(340, 300, 210, 60))
        self.akademisyen_butonu.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.akademisyen_butonu.setStyleSheet("background-color: rgb(208, 227, 255);")
        self.akademisyen_butonu.setObjectName("akademisyen_butonu")
        self.ogrenci_butonu = QtWidgets.QPushButton(self.centralwidget)
        self.ogrenci_butonu.setGeometry(QtCore.QRect(340, 390, 210, 60))
        self.ogrenci_butonu.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.ogrenci_butonu.setStyleSheet("background-color: rgb(208, 227, 255);")
        self.ogrenci_butonu.setObjectName("ogrenci_butonu")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1001, 231))
        self.frame.setStyleSheet("background-color: rgb(239, 126, 24);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(250, 60, 591, 71))
        self.label.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 201, 181))
        self.label_2.setStyleSheet("background-color: rgb(0, 152, 188);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("mtu.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(670, 200, 241, 20))
        self.label_4.setStyleSheet("color: rgb(94, 129, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ANA PENCERE"))
        self.akademisyen_butonu.setText(_translate("MainWindow", "AKADMESİYEN GİRİŞİ"))
        self.ogrenci_butonu.setText(_translate("MainWindow", "ÖĞRENCİ GİRİŞİ"))
        self.label.setText(_translate("MainWindow", "MALATYA TURGUT ÖZAL ÜNİVERSİTESİ"))
        self.label_4.setText(_translate("MainWindow", "BİLİM, EMEK, ÖZVERİ..."))
